### ISSUE TITLE
Show the User a Menu

### ISSUE THREAD

**Issue by joebochill** [andrianost/SwingEssentials#7]
We need the hamburger menu to open up and show the different menu options:
- Home
- Your Lessons
- Redeem a Lesson
- Order a Lesson
- Help
- About
- Settings

This should also include the section with the user's avatar and name.

**Comment by andrianost** [comment]
Menu is in progress

**Comment by andrianost** [comment]
Done, although I didn't include an avatar.  This can be done if deemed necessary.
